/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myapplication;



/**
 *
 * @author JRK PISONET
 */
public class Calculator extends javax.swing.JFrame {
    private double num1 = 0;
private double num2 = 0;
private String operator = "";

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculator.class.getName());


    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        percent = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        AC = new javax.swing.JButton();
        subtract = new javax.swing.JButton();
        one = new javax.swing.JButton();
        four = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        two = new javax.swing.JButton();
        five = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        three = new javax.swing.JButton();
        six = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        addition = new javax.swing.JButton();
        devide = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        decimals = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        summation = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        percent.setBackground(new java.awt.Color(204, 204, 204));
        percent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        percent.setText("%");
        percent.addActionListener(this::percentActionPerformed);
        getContentPane().add(percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 119, 66));

        delete.setBackground(new java.awt.Color(204, 204, 204));
        delete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delete.setText("DEL");
        delete.addActionListener(this::deleteActionPerformed);
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 251, 119, 66));

        AC.setBackground(new java.awt.Color(204, 204, 204));
        AC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AC.setText("C");
        AC.addActionListener(this::ACActionPerformed);
        getContentPane().add(AC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 119, 66));

        subtract.setBackground(new java.awt.Color(255, 102, 0));
        subtract.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        subtract.setText("-");
        subtract.addActionListener(this::subtractActionPerformed);
        getContentPane().add(subtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 119, 66));

        one.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        one.setText("1");
        one.addActionListener(this::oneActionPerformed);
        getContentPane().add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 119, 66));

        four.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        four.setText("4");
        four.addActionListener(this::fourActionPerformed);
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 119, 66));

        seven.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        seven.setText("7");
        seven.addActionListener(this::sevenActionPerformed);
        getContentPane().add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 119, 66));

        two.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        two.setText("2");
        two.addActionListener(this::twoActionPerformed);
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 119, 66));

        five.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        five.setText("5");
        five.addActionListener(this::fiveActionPerformed);
        getContentPane().add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 119, 66));

        eight.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eight.setText("8");
        eight.addActionListener(this::eightActionPerformed);
        getContentPane().add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 119, 66));

        three.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        three.setText("3");
        three.addActionListener(this::threeActionPerformed);
        getContentPane().add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 329, 119, 66));

        six.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        six.setText("6");
        six.addActionListener(this::sixActionPerformed);
        getContentPane().add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 119, 66));

        nine.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nine.setText("9");
        nine.addActionListener(this::nineActionPerformed);
        getContentPane().add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 119, 66));

        addition.setBackground(new java.awt.Color(255, 102, 0));
        addition.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addition.setText("+");
        addition.addActionListener(this::additionActionPerformed);
        getContentPane().add(addition, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 119, 66));

        devide.setBackground(new java.awt.Color(255, 102, 0));
        devide.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        devide.setText("÷");
        devide.addActionListener(this::devideActionPerformed);
        getContentPane().add(devide, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 251, 119, 66));

        multiply.setBackground(new java.awt.Color(255, 102, 0));
        multiply.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        multiply.setText("X");
        multiply.addActionListener(this::multiplyActionPerformed);
        getContentPane().add(multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 119, 66));

        zero.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        zero.setText("0");
        zero.addActionListener(this::zeroActionPerformed);
        getContentPane().add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 250, 66));

        decimals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        decimals.setText(".");
        decimals.addActionListener(this::decimalsActionPerformed);
        getContentPane().add(decimals, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, 119, 66));

        equals.setBackground(new java.awt.Color(153, 153, 0));
        equals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        equals.setText("=");
        equals.addActionListener(this::equalsActionPerformed);
        getContentPane().add(equals, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 119, 66));

        summation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        summation.addActionListener(this::summationActionPerformed);
        getContentPane().add(summation, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 115, 570, 102));

        back.setText("BACK");
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, 80, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JRK PISONET\\Downloads\\994024.png")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void percentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentActionPerformed
        // TODO add your handling code here:
        try {
        double value = Double.parseDouble(summation.getText());
        value = value / 100; // convert to percent
        summation.setText(String.valueOf(value));
    } catch (NumberFormatException e) {
        summation.setText("Error");
    }
    }//GEN-LAST:event_percentActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
          String text = summation.getText();
    if (!text.isEmpty()) {
        summation.setText(text.substring(0, text.length() - 1));
    }
    }//GEN-LAST:event_deleteActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
        // TODO add your handling code here:
        summation.setText("");
    num1 = 0;
    num2 = 0;
    operator = "";

    }//GEN-LAST:event_ACActionPerformed

    private void subtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(summation.getText());
    operator = "-";
    summation.setText("");

    }//GEN-LAST:event_subtractActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        summation.setText(summation.getText()+"1");
    }//GEN-LAST:event_oneActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
       summation.setText(summation.getText() + "4");
    }//GEN-LAST:event_fourActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
         summation.setText(summation.getText() + "7");
    }//GEN-LAST:event_sevenActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
         summation.setText(summation.getText() + "2");
    }//GEN-LAST:event_twoActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
         summation.setText(summation.getText() + "5");
    }//GEN-LAST:event_fiveActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
         summation.setText(summation.getText() + "8");
    }//GEN-LAST:event_eightActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
         summation.setText(summation.getText() + "3");
    }//GEN-LAST:event_threeActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
         summation.setText(summation.getText() + "6");
    }//GEN-LAST:event_sixActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
         summation.setText(summation.getText() + "9");
    }//GEN-LAST:event_nineActionPerformed

    private void additionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(summation.getText());
    operator = "+";
    summation.setText("");

    }//GEN-LAST:event_additionActionPerformed

    private void devideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devideActionPerformed
        // TODO add your handling code here:
          num1 = Double.parseDouble(summation.getText());
    operator = "/";
    summation.setText("");
    }//GEN-LAST:event_devideActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(summation.getText());
    operator = "*";
    summation.setText("");

    }//GEN-LAST:event_multiplyActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
         summation.setText(summation.getText() + "0");
    }//GEN-LAST:event_zeroActionPerformed

    private void decimalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalsActionPerformed
        // TODO add your handling code here:
         if (!summation.getText().contains(".")) {
        summation.setText(summation.getText() + ".");
    }
    }//GEN-LAST:event_decimalsActionPerformed

    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        // TODO add your handling code here:
        num2 = Double.parseDouble(summation.getText());
    double result = 0;

    switch (operator) {
        case "+": result = num1 + num2; break;
        case "-": result = num1 - num2; break;
        case "*": result = num1 * num2; break;
        case "/": 
            if (num2 != 0) result = num1 / num2;
            else {
                summation.setText("Error");
                return;
            }
            break;
        case "%": result = num1 % num2; break;
    }

    summation.setText(String.valueOf(result));
    }//GEN-LAST:event_equalsActionPerformed

    private void summationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_summationActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
                                     // Fade out Calculator
 
  
     new Mainframe().setVisible(true);
    // Close the Mainframe window
    this.dispose();


    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JButton addition;
    private javax.swing.JButton back;
    private javax.swing.JButton decimals;
    private javax.swing.JButton delete;
    private javax.swing.JButton devide;
    private javax.swing.JButton eight;
    private javax.swing.JButton equals;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton percent;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton subtract;
    private javax.swing.JTextField summation;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
