/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myapplication;

import java.io.BufferedWriter;

/**
 *
 * @author JRK PISONET
 */
public class Createaccount extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Createaccount.class.getName());

    /**
     * Creates new form Createaccount
     */
    public Createaccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CREATE = new javax.swing.JButton();
        Passform = new javax.swing.JPasswordField();
        Firstname = new javax.swing.JTextField();
        Lastname = new javax.swing.JTextField();
        Gmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("CREATE ACCOUNT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("LAST NAME:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("FIRST NAME:");
        jLabel4.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jLabel4CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 110, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("EMAIL:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("PASSWORD:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, -1, -1));

        CREATE.setBackground(new java.awt.Color(153, 153, 153));
        CREATE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CREATE.setText("CREATE");
        CREATE.addActionListener(this::CREATEActionPerformed);
        getContentPane().add(CREATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 250, 44));

        Passform.setBackground(new java.awt.Color(153, 153, 153));
        Passform.addActionListener(this::PassformActionPerformed);
        getContentPane().add(Passform, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 250, 30));

        Firstname.setBackground(new java.awt.Color(153, 153, 153));
        Firstname.addActionListener(this::FirstnameActionPerformed);
        getContentPane().add(Firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 250, 30));

        Lastname.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(Lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 250, 30));

        Gmail.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(Gmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, 250, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JRK PISONET\\Downloads\\wp9406298.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1860, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel4CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4CaretPositionChanged

    private void CREATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEActionPerformed
        // TODO add your handling code here:
 String firstName = Firstname.getText().trim();
String lastName = Lastname.getText().trim();
String email = Gmail.getText().trim();
String password = new String(Passform.getPassword()).trim();

if (firstName.isEmpty() || lastName.isEmpty() || email.isEmpty() || password.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "All fields must be filled!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

try {
    java.io.FileWriter fw = new java.io.FileWriter("users.txt", true);
java.io.BufferedWriter bw = new java.io.BufferedWriter(fw);
bw.write(firstName + "," + lastName + "," + email + "," + password);
bw.newLine();
bw.close();
fw.close();

    javax.swing.JOptionPane.showMessageDialog(this, "Account Created Successfully");

    new login().setVisible(true);
    this.dispose();

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error saving account: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_CREATEActionPerformed

    private void FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new login().setVisible(true);
    // Close the submittedby window
    this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void PassformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassformActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Createaccount().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CREATE;
    private javax.swing.JTextField Firstname;
    private javax.swing.JTextField Gmail;
    private javax.swing.JTextField Lastname;
    private javax.swing.JPasswordField Passform;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
