/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myapplication;
import javax.swing.SwingUtilities;
import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JFrame;

/**
 *
 * @author JRK PISONET
 */
public class Mainframe extends javax.swing.JFrame {
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mainframe.class.getName());
   public Mainframe(String firstName, String lastName) {
    initComponents(); // must be first
    Name.setText(firstName + " " + lastName);
}    

    

    /**
     * Creates new form Mainframe
     */
    public Mainframe() {
        initComponents();
    }

    Mainframe(String user) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel6 = new javax.swing.JLabel();
        Calculator = new javax.swing.JButton();
        Snakegame = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        developedby = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");
        jMenu3.add(jMenu4);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\JRK PISONET\\Documents\\NetBeansProjects\\Myapplication\\src\\myapplication\\betterttv-cute.gif")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Calculator.setBackground(new java.awt.Color(153, 153, 153));
        Calculator.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Calculator.setForeground(new java.awt.Color(204, 102, 0));
        Calculator.setText("CALCULATOR");
        Calculator.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Calculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calculator.addActionListener(this::CalculatorActionPerformed);
        getContentPane().add(Calculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 600, 90));

        Snakegame.setBackground(new java.awt.Color(153, 153, 153));
        Snakegame.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Snakegame.setText("SNAKE GAME");
        Snakegame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Snakegame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Snakegame.addActionListener(this::SnakegameActionPerformed);
        getContentPane().add(Snakegame, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 600, 88));

        exit.setBackground(new java.awt.Color(153, 153, 153));
        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setText("EXIT");
        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(this::exitActionPerformed);
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 600, 600, 88));

        Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("DASHBOARD");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 515, 34));

        developedby.setBackground(new java.awt.Color(153, 153, 153));
        developedby.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        developedby.setText("DEVELOPED BY:");
        developedby.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        developedby.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        developedby.addActionListener(this::developedbyActionPerformed);
        getContentPane().add(developedby, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 600, 63));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\JRK PISONET\\Downloads\\gallery-1497533116-not-dead.gif")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 600, 350));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\JRK PISONET\\Documents\\NetBeansProjects\\Myapplication\\src\\myapplication\\rotatingdandelion.gif")); // NOI18N
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.lightGray));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 600, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JRK PISONET\\Downloads\\994024.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2610, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void developedbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_developedbyActionPerformed
  new submittedby().setVisible(true);
  this.dispose();
    }//GEN-LAST:event_developedbyActionPerformed

    private void CalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatorActionPerformed
new Calculator ().setVisible(true);
this.dispose();
    }//GEN-LAST:event_CalculatorActionPerformed

    private void SnakegameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnakegameActionPerformed
 JFrame f = new JFrame ("Snake Game");
 Snakegame game = new Snakegame();
 f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
 f.add(game, BorderLayout.CENTER);
 
 JPanel controls = new JPanel();
 JButton restartBtn = new JButton("Restart");
 JButton backBtn = new JButton("Back");
 controls.add(restartBtn);
 controls.add(backBtn);
 f.add(controls, BorderLayout.SOUTH);
 
 restartBtn.addActionListener(e -> {
     game.resetGame();
     game.timer.restart();
 });
 backBtn.addActionListener(e -> {
     f.dispose();
     new Mainframe().setVisible(true);
 });
 f.pack();
 f.setVisible(true);
 this.dispose();
 
  




    }//GEN-LAST:event_SnakegameActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mainframe().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calculator;
    private javax.swing.JLabel Name;
    private javax.swing.JButton Snakegame;
    private javax.swing.JButton developedby;
    private javax.swing.JButton exit;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
}
